#!/bin/sh
# vim:ft=sh

CONF="$1"
CMD_MUST_HAVE="mount bash mintty cygwin-console-helper"
DIST_DIR="dist"
BIN_DIR="$DIST_DIR/bin"
HOME_DIR="$DIST_DIR/home"
MANIFEST_FILE="$DIST_DIR/manifest"
DEPENDENCY_FILE="$DIST_DIR/dependencies"

die()
{
  local ret=$1
  shift
  echo "ERROR:$@"
  exit $ret
}

# Prepare distribution directory
echo "Initializing directories ..."
rm -rf "$DIST_DIR"
mkdir -p "$DIST_DIR"
mkdir -p "$BIN_DIR"
mkdir -p "$HOME_DIR"

# Pre-process each listed command
for cmd in `cat "$CONF"` $CMD_MUST_HAVE; do
  echo "Checking '$cmd' ..."
  cmdAbsPath=`which $cmd 2>/dev/null` || die 1 "'$cmd' not found"
  echo "$cmdAbsPath" >> "$MANIFEST_FILE"
  ldd "$cmdAbsPath" | sed -n -e '/\/cygdrive\//d' -e 's_^.*=>[ ]*\([^ ]*\).*$_\1_gp' >> "$DEPENDENCY_FILE"
done

# Copy commands
for cmd in `sort "$MANIFEST_FILE" | uniq`; do
  echo "Copying command '$cmd' ..."
  cp -L "$cmd" "$BIN_DIR/" || die 2 "Couldn't copy '$cmd'"
done

# Copy depencencies
for dep in `sort "$DEPENDENCY_FILE" | uniq`; do
  echo "Copying dependency '$dep' ..."
  cp -L "$dep" "$BIN_DIR/" || die 3 "Couldn't copy '$dep'"
done

# Install the startup batch file
START_BATCH_FILE="$DIST_DIR/run.bat"
echo "Creating startup batch file '$START_BATCH_FILE' "
cat >"$START_BATCH_FILE" <<EOF
for /F %%A in ('cd') do set WD=%%A
bin\mount %WD%\ /
bin\mount %WD%\bin /usr/bin
bin\mount %WD%\lib /usr/lib

set HOME=%WD%\home
start bin\mintty.exe -e /bin/bash --login -i -
EOF
unix2dos "$START_BATCH_FILE" 2>/dev/null
chmod a+x "$START_BATCH_FILE"
