#!/bin/sh
# vim:ft=sh

CONF="$1"
CMD_MUST_HAVE="mount bash mintty cygwin-console-helper"
DIST_DIR="dist"
BIN_DIR="$DIST_DIR/bin"
SHARE_DIR="$DIST_DIR/usr/share"
HOME_DIR="$DIST_DIR/home"
MANIFEST_FILE="$DIST_DIR/manifest"
DEPENDENCY_FILE="$DIST_DIR/dependencies"

die()
{
  local ret=$1
  shift
  echo "ERROR:$@"
  exit $ret
}

# Prepare distribution directory
echo "Initializing directories ..."
rm -rf "$DIST_DIR"
mkdir -p "$DIST_DIR"
mkdir -p "$BIN_DIR"
mkdir -p "$SHARE_DIR"
mkdir -p "$HOME_DIR"

# Pre-process each listed command
for cmd in `cat "$CONF"` $CMD_MUST_HAVE; do
  echo "Checking '$cmd' ..."
  cmdAbsPath=`which $cmd 2>/dev/null` || die 1 "'$cmd' not found"
  echo "$cmdAbsPath" >> "$MANIFEST_FILE"
  ldd "$cmdAbsPath" | sed -n -e '/\/cygdrive\//d' -e 's_^.*=>[ ]*\([^ ]*\).*$_\1_gp' >> "$DEPENDENCY_FILE"
done

# Copy commands
for cmd in `sort "$MANIFEST_FILE" | uniq`; do
  echo "Copying command '$cmd' ..."
  cp -L "$cmd" "$BIN_DIR/" || die 2 "Couldn't copy '$cmd'"
done

# Copy depencencies
for dep in `sort "$DEPENDENCY_FILE" | uniq`; do
  echo "Copying dependency '$dep' ..."
  cp -L "$dep" "$BIN_DIR/" || die 3 "Couldn't copy '$dep'"
done

# Setup terminfo
echo "Copying 'terminfo' ..."
cp -rL /usr/share/terminfo "$SHARE_DIR/"

# Install the startup batch file
START_BATCH_FILE="$DIST_DIR/run.bat"
echo "Creating startup batch file '$START_BATCH_FILE' ..."
cat >"$START_BATCH_FILE" <<EOF
for /F %%A in ('cd') do set WD=%%A
bin\mount %WD%\ /

set HOME=%WD%\home
start bin\mintty.exe -e /bin/bash --login -i -
EOF
unix2dos "$START_BATCH_FILE" 2>/dev/null
chmod a+x "$START_BATCH_FILE"

# Setup shell startup file
SHELL_STARTUP_FILE="$HOME_DIR/.profile"
echo "Creating shell startup file '$SHELL_STARTUP_FILE' ..."
cat >"$SHELL_STARTUP_FILE" <<EOF
export PATH=/bin
case "\$-" in
  *i*)
    # Aliases
    alias ls='ls --color'
    alias rm='rm -i'
    alias mv='mv -i'
    alias cp='cp -i'
    ;;
esac
EOF

# Setup mintty configuration file
MINTTY_CONF_FILE="$HOME_DIR/.minttyrc"
echo "Creating mintty configuration file '$MINTTY_CONF_FILE' ..."
cat >"$MINTTY_CONF_FILE" <<EOF
BoldAsFont=no
Font=Courier New
FontHeight=12
Locale=en_US
Charset=UTF-8
Transparency=medium
CursorType=block
Term=xterm-256color
Scrollbar=none
EOF
